<?php

/**
 * @package
 * @author     David Pommer (conlabz GmbH) <david.pommer@conlabz.de>
 */
class Conlabz_Regions_Model_Continents
{
    protected $continentCodes = [
        'Europe' => 'EU',
        'Africa' => 'AF',
        'Asia' => 'AS',
        'Oceania' => 'OC',
        'Antarctica' => 'AN',
        'North America' => 'NA',
        'South America' => 'SA'
    ];

    /**
     * @var string[][]
     */
    protected $countriesToContinents = [
        'Europe' => [
            'DE',
            'GG',
            'VA',
            'HU',
            'IS',
            'IE',
            'IM',
            'IT',
            'JE',
            'LV',
            'LI',
            'LT',
            'LU',
            'MK',
            'MT',
            'MD',
            'MC',
            'ME',
            'NL',
            'NO',
            'RO',
            'RU',
            'RS',
            'SK',
            'SI',
            'ES',
            'SJ',
            'SE',
            'CH',
            'UA',
            'GB',
            'GI',
            'GR',
            'AX',
            'AL',
            'AD',
            'AT',
            'BA',
            'BY',
            'BE',
            'BG',
            'CZ',
            'DK',
            'EE',
            'HR',
            'FI',
            'FR',
            'FO',
            'PL',
            'PT',
            'SM',
        ],
        'Africa' => [
            'GH',
            'DZ',
            'AO',
            'BJ',
            'BW',
            'BF',
            'BI',
            'CM',
            'CV',
            'CF',
            'TD',
            'KM',
            'CD',
            'CG',
            'CI',
            'DJ',
            'EG',
            'GQ',
            'ER',
            'ET',
            'GA',
            'GM',
            'GN',
            'GW',
            'KE',
            'LS',
            'LR',
            'LY',
            'MG',
            'MW',
            'ML',
            'MR',
            'MU',
            'YT',
            'MA',
            'MZ',
            'NA',
            'NE',
            'NG',
            'RE',
            'RW',
            'SH',
            'ST',
            'SN',
            'SC',
            'SL',
            'SO',
            'ZA',
            'SD',
            'SZ',
            'TZ',
            'TG',
            'TN',
            'UG',
            'EH',
            'ZM',
            'ZW',
        ],
        'Asia' => [
            'AF',
            'AM',
            'AZ',
            'BH',
            'BD',
            'BT',
            'IO',
            'BN',
            'KH',
            'CN',
            'CX',
            'CC',
            'CY',
            'GE',
            'HK',
            'IN',
            'ID',
            'IR',
            'IQ',
            'IL',
            'JP',
            'JO',
            'KZ',
            'KP',
            'KR',
            'KW',
            'KG',
            'LA',
            'LB',
            'MO',
            'MY',
            'MV',
            'MN',
            'MM',
            'NP',
            'OM',
            'PK',
            'PS',
            'PH',
            'QA',
            'SA',
            'SG',
            'LK',
            'SY',
            'TW',
            'TJ',
            'TH',
            'TL',
            'TR',
            'TM',
            'AE',
            'UZ',
            'VN',
            'YE',
        ],
        'Oceania' => [
            'AU',
            'AS',
            'CK',
            'FJ',
            'PF',
            'GU',
            'KI',
            'MH',
            'FM',
            'NR',
            'NC',
            'NZ',
            'NU',
            'NF',
            'MP',
            'PW',
            'PG',
            'PN',
            'WS',
            'SB',
            'TK',
            'TO',
            'TV',
            'UM',
            'VU',
            'WF',
        ],
        'Antarctica' => [
            'AQ',
            'BV',
            'TF',
            'HM',
            'GS',
        ],
        'North America' => [
            'AI',
            'AW',
            'AG',
            'BS',
            'BB',
            'BZ',
            'BM',
            'CA',
            'KY',
            'VG',
            'CR',
            'CU',
            'DM',
            'DO',
            'SV',
            'GL',
            'GD',
            'GP',
            'GT',
            'HT',
            'HN',
            'JM',
            'MQ',
            'MX',
            'MS',
            'NI',
            'PA',
            'PR',
            'BL',
            'KN',
            'LC',
            'MF',
            'PM',
            'VC',
            'AN',
            'TT',
            'TC',
            'US',
            'VI',
        ],
        'South America' => [
            'AR',
            'BO',
            'CL',
            'CO',
            'BR',
            'EC',
            'FK',
            'GF',
            'GY',
            'PY',
            'PE',
            'SR',
            'UY',
            'VE',
        ]
    ];

    /**
     * @return string[][]
     */
    public function getContinents()
    {
        return $this->countriesToContinents;
    }

    /**
     * @param $continent
     * @return false|string
     */
    public function getContinentCodeFromName($continent)
    {
        return $this->continentCodes[$continent] ?? false;
    }
}
