<?php /* @var $this Mage_Review_Block_Product_View */ ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_skylotecHelper = $this->helper('skylotec') ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="product-view-top">
    <div class="product-essential">
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="qty" value="1" id="qty-hidden">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
            <header class="box-title">
                <div class="headline">
                    <h1>
                        <?php if ($categoryIcon = $_skylotecHelper->getCategoryIcon($_product)): ?>
                            <span class="icon-category icon-skylotec" style="background-image: url(<?php echo Mage::getBaseUrl('media').'catalog/category/icons/'. $categoryIcon ?>)"></span>
                        <?php endif; ?>
                        <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                    </h1>
                    <?php if ($marketing_title = $_helper->productAttribute($_product, $_product->getMarketingTitle(), 'marketing_title')): ?>
                    <h2><?php echo $marketing_title ?></h2>
                    <?php endif; ?>
                </div>
                <div class="subtitle">
                    <?php foreach ($_skylotecHelper->getBranches($_product) as $branche): ?>
                    <a href="<?php echo $branche->getUrl() ?>">
                        <span class="icon-category icon-skylotec" style="-webkit-mask: url(<?php echo Mage::getBaseUrl('media').'catalog/category/icons/'. $branche->getIcon() ?>) no-repeat 50% 50%;mask: url(<?php echo Mage::getBaseUrl('media').'catalog/category/icons/'. $branche->getIcon() ?>) no-repeat 50% 50%"></span>
                    </a>
                    <?php endforeach; ?>
                </div>
            </header>
            <div class="product-img" id="product-image-main">
                <?php echo $this->getChildHtml('main-image') ?>
            </div>
            <div class="product-options">
                <?php echo $this->getChildHtml('addtocart') ?>
            </div>
        </form>
        <script type="text/javascript">
        //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                       form.action = url;
                    }
                    var e = null;
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
        //]]>
        </script>
    </div>
</div>
<div class="product-view">
    <div class="product-collateral tabs">
        <?php echo $this->getChildHtml('tabs') ?>
        <?php foreach ($this->getChildGroup('tabs', 'getChildHtml') as $alias => $html):?>
        <div class="box-collateral box-<?php echo $alias ?>" id="<?php echo $alias ?>">
            <?php echo $html; ?>
        </div>
        <?php endforeach;?>
    </div>
    <?php echo $this->getChildHtml('upsell_products') ?>
    <?php echo $this->getChildHtml('product_additional_data') ?>
</div>
