<?php
if ($blockId = $this->getBlockId()):
$block = Mage::getModel('cms/block')
    ->setStoreId(Mage::app()->getStore()->getId())
    ->load($blockId);
if ($block->getIsActive()):
    /* @var $helper Mage_Cms_Helper_Data */
    $helper = Mage::helper('cms');
    $processor = $helper->getBlockTemplateProcessor();
    $html = $processor->filter($block->getContent());
?>
<div class="skylotec-home">
    <div class="skylotec-home-text">
        <?php echo $html ?>
    </div>
    <a href="<?php echo Mage::getUrl('') ?><?php echo $this->__('company/about-us.html') ?>" class="btn"><?php echo $this->__('About us') ?></a>
</div>
<?php endif ?>
<?php endif ?>
