<?php
/* @var $this Conlabz_Skylotec_Block_News_Archive */
$archives = $this->getArchivesYearMonths();
?>
<?php if (count($archives) > 0): ?>
	<div class="block block-blog block-blog-archives">
		<?php if ($title = $this->getTitle()): ?>
			<div class="block-title">
				<strong><span><?php echo $this->__($title) ?></span></strong>
			</div>
		<?php endif; ?>
		<div class="block-content">
			<div id="wp-archive-list">
            <?php foreach($archives as $year => $archives): ?>
                <div class="clearfix">
                    <div class="archive-year">
                        <?php echo $year ?>
                    </div>
                    <div class="archive-months">
                    <?php foreach($archives as $archive): ?>
                        <div class="archive-month <?php if ($this->isCurrentArchive($archive)): ?> active<?php endif; ?>">
                            <a href="<?php echo $this->getArchiveUrl($archive) ?>">
                                <?php echo $this->__($archive->getMonth()) ?>
                                <?php echo $archive->getYear() ?>
                            </a>
                        </div>
                    <?php endforeach ?>
                    </div>
                </div>
            <?php endforeach; ?>
			</div>
		</div>
	</div>
<?php endif; ?>
