<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php if ($images = $this->getImageCollection()): ?>
	<?php $columns = $this->getColumns() ?>
	<?php $imageCount = count($images) ?>
	<div class="gallery galleryid-<?php echo $this->getPost()->getId() ?> gallery-columns-<?php echo $this->getColumns() ?> gallery-size-<?php echo $this->getSize() ?> gallery<?php echo $this->getGalleryIt() ?>" id="gallery-<?php echo $this->getGalleryIt() ?>">
		<?php $it = 0; foreach($images as $image): ?>
		<?php $caption = trim($this->escapeHtml($image->getPostExcerpt())); ?>
        <dl class="gallery-item" style="float: left; width: <?php echo floor(100 / $this->getColumns()) ?>%;">
			<dt class="gallery-icon">
				<a title="<?php echo $caption ?>" rel="gallery<?php echo $this->getGalleryIt() ?>" href="<?php echo $image->getFullSizeImage() ?>"><img title="<?php echo $image->getPostTitle() ?>" alt="<?php echo $image->getPostTitle() ?>" class="attachment-<?php echo $this->getSize() ?>" src="<?php echo $image->getImageByType($this->getSize()) ? $image->getImageByType($this->getSize()) : $image->getAvailableImage() ?>" /></a>
			</dt>
			<?php if ($caption): ?>
				<dd class="wp-caption-text gallery-caption"><?php echo $caption ?></dd>
			<?php endif; ?>
		</dl>
		<?php ++$it; endforeach; ?>
	</div>
	<div class="clearer"></div>
<?php endif; ?>
