<?php
/**
 * Shoping cart header
 */

/* @var $this Mage_Checkout_Block_Cart_Sidebar */
?>
<?php $_cartQty = $this->getSummaryCount() ?>
<a class="quick-item" href="<?php echo $this->getUrl('checkout/cart') ?>"<?php echo $_cartQty > 0 ? ' class="active"': '' ?>>
    <span>
        <?php echo $this->__('Cart (%s)', (int) $_cartQty) ?>
    </span>
</a>
<?php if ($_cartQty > 0): ?>
<div class="cart-summary">
    <?php $_items = $this->getRecentItems() ?>
    <table id="cart-sidebar" class="mini-products-list">
    <?php foreach($_items as $_item): ?>
        <?php echo $this->getItemHtml($_item) ?>
    <?php endforeach; ?>
        <tr>
            <td colspan="2" class="subtotal-label">
                <?php echo $this->__('Subtotal:') ?>
            </td>
            <td class="subtotal price">
                <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
            </td>
            <td>&nbsp;</td>
        </tr>
    </table>
    <?php if($this->isPossibleOnepageCheckout()): ?>
    <div class="actions">
        <?php echo $this->getChildHtml('extra_actions') ?>
        <a href="<?php echo $this->getCheckoutUrl() ?>" title="<?php echo $this->__('Checkout') ?>" class="button">
            <?php echo $this->__('Checkout') ?>
        </a>
    </div>
    <?php endif; ?>
</div>
<?php endif; ?>


            <?php /*
            <p class="subtotal">
                <?php if ($this->canApplyMsrp()): ?>
                    <span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                <?php else: ?>
                    <span class="label"><?php echo $this->__('Cart Subtotal:') ?></span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                    <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                        <br />(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
                    <?php endif; ?>
                <?php endif; ?>
            </p>*/ ?>