<?php
/* @var $this Mage_Page_Block_Html_Header */
?>
<div class="header-container">
    <header class="header">
        <?php if ($this->getIsHomePage()): ?><h1><?php endif; ?>
        <a class="logo" href="<?php echo $this->getUrl('') ?>">
            <img src="<?php echo $this->getSkinUrl('images/logo.png') ?>?v=1458305117" alt="<?php echo $this->getLogoAlt() ?>">
        </a>
        <button type="button" class="toggle-nav" data-target=".header .nav">
            <span><?php echo $this->__('Open nav') ?></span>
        </button>
        <?php if ($this->getIsHomePage()): ?></h1><?php endif; ?>
        <div class="menu">
            <nav class="nav">
                <?php echo $this->getChildHtml('navigation') ?>
            </nav>
            <nav class="quick-access">
                <ul>
                    <li class="quick-language"><?php echo $this->getChildHtml('language') ?></li>
                    <li class="quick-cart"><?php echo $this->getChildHtml('cart') ?></li>
                    <li class="quick-contact"><a class="quick-item" href="<?php echo $this->getUrl('contacts') ?>"><span><?php echo $this->__('Contact') ?></span></a></li>
                    <li class="quick-homebase"><a class="quick-item" href="<?php echo "https://app.myhomebase.de"; ?>" target="_blank"><span><?php echo $this->__('homebase') ?></span></a></li>
                    <li class="quick-search <?php if ($this->helper('catalogsearch')->getEscapedQueryText()) echo 'active' ?>"><?php echo $this->getChildHtml('search') ?>
                </ul>
            </nav>
        </div>
    </header>
    <nav class="subnav">
        <div class="subnav-inner">
            <?php echo $this->getChildHtml('subnavigation') ?>
            <a href="#" id="subnav-prev" class="s-left"><span>prev</span></a>
            <a href="#" id="subnav-next" class="s-right"><span>next</span></a>
        </div>
    </nav>
</div>
